# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Despite these docs being long out of date, file added by ProfYaffle 14 June 2023 to reflect new readthedocs build requirements.
# Read more at https://blog.readthedocs.com/migrate-configuration-v2/

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

mkdocs:
  configuration: mkdocs.yml

# Below is part of the default template - commented out as we have no dependencies that I can remember.

# From the deprecation notice:

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

# Optionally declare the Python requirements required to build your docs

# python:
#   install:
#   - requirements: docs/requirements.txt
